export const FETCH_TRIPS_REQUEST = 'FETCH_TRIPS_REQUEST';
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS';
export const FETCH_TRIPS_FAILURE = 'FETCH_TRIPS_FAILURE';

export const SAVE_TRIPS_REQUEST = 'SAVE_TRIPS_REQUEST';
export const SAVE_TRIPS_SUCCESS = 'SAVE_TRIPS_SUCCESS';
export const SAVE_TRIPS_FAILURE = 'SAVE_TRIPS_FAILURE';