export const FETCH_MEDIA_REQUEST = 'FETCH_MEDIA_REQUEST';
export const FETCH_MEDIA_SUCCESS = 'FETCH_MEDIA_SUCCESS';
export const FETCH_MEDIA_FAILURE = 'FETCH_MEDIA_FAILURE';

export const FETCH_FAVOURITES_REQUEST = 'FETCH_FAVOURITES_REQUEST';
export const FETCH_FAVOURITES_SUCCESS = 'FETCH_FAVOURITES_SUCCESS';
export const FETCH_FAVOURITES_FAILURE = 'FETCH_FAVOURITES_FAILURE';

export const SAVE_MEDIA_REQUEST = 'SAVE_MEDIA_REQUEST';
export const SAVE_MEDIA_SUCCESS = 'SAVE_MEDIA_SUCCESS';
export const SAVE_MEDIA_FAILURE = 'SAVE_MEDIA_FAILURE';
export const UNSAVE_MEDIA_SUCCESS = 'UNSAVE_MEDIA_SUCCESS';
export const UNSAVE_MEDIA_FAILURE = 'UNSAVE_MEDIA_FAILURE';

export const FETCH_VIDEOS_REQUEST = 'FETCH_VIDEOS_REQUEST';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE';

export const FETCH_PLACES_REQUEST = 'FETCH_PLACES_REQUEST';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE';

export const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST';
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE';

export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

export const SET_DISPLAY_FILTER_MEDIA = 'SET_DISPLAY_FILTER_MEDIA';
export const SET_DISPLAY_FILTER_VIDEO = 'SET_DISPLAY_FILTER_VIDEO';
export const SET_DISPLAY_FILTER_PLACE = 'SET_DISPLAY_FILTER_PLACE';
export const SET_DISPLAY_FILTER_RESTAURANT = 'SET_DISPLAY_FILTER_RESTAURANT';
export const SET_DISPLAY_FILTER_EVENT = 'SET_DISPLAY_FILTER_EVENT';

export const CLEAR_PLACES = 'CLEAR_PLACES';
export const CLEAR_MEDIA = 'CLEAR_MEDIA';
export const CLEAR_VIDEOS = 'CLEAR_VIDEOS';
export const CLEAR_RESTAURANTS = 'CLEAR_RESTAURANTS';
export const CLEAR_EVENTS = 'CLEAR_EVENTS';
